[cite_start]name: CI Test [cite: 39]
[cite_start]on: [cite: 40]
  [cite_start]push: [cite: 41]
    [cite_start]branches: [cite: 42]
      - [cite_start]main [cite: 45] # Le pipeline se déclenche sur la branche 'main'

[cite_start]jobs: [cite: 43]
  [cite_start]build: [cite: 44]
    [cite_start]runs-on: ubuntu-latest [cite: 46] # Utilise une machine virtuelle Linux pour l'exécution
    [cite_start]steps: [cite: 47]
      - [cite_start]name: Checkout du dépôt [cite: 48]
        [cite_start]uses: actions/checkout@v3 [cite: 49] # Télécharge votre code dans la machine virtuelle

      - [cite_start]name: Test simple [cite: 50]
        [cite_start]run: echo "CI Pipeline exécuté avec succès !" [cite: 51] # Étape de "test" basique